webnark-rails/config/routes.rb
WebnarkRails::Application.routes.draw do

  devise_for :users

  resources :answers
  resources :report_choices
  resources :report_items
  resources :report_categories

  root :to => 'high_voltage/pages#show', id: 'home'

  get '/search/:query', to: 'services#search'
  get '/search', to: 'services#search'

  get '/services/:id/full', to: 'services#full', as: :full_report
  post "/services/add_comment" => "services#add_comment", :as => "add_comment_to_services", :via => [:services]
  get '/services/unmoderated', to: 'services#unmoderated', as: :unmoderated_services
  get '/services/flagged', to: 'services#flagged', as: :flagged_services
  get '/services/:id/report', to: 'services#report', as: :report_service
  get '/services/:id/moderate', to: 'services#moderate', as: :moderate_service
  get '/services/:id/unreport', to: 'services#unreport', as: :unreport_service
  get '/services/tagged' => 'services#tagged', :as => 'tagged'
  resources :services

  get '/comments/:id/report', to: 'comments#report', as: :report_comment
  get '/comments/flagged', to: 'comments#flagged', as: :flagged_comments
  resources :comments

  get '/pages/about', to: 'high_voltage/pages#show', id: 'about'

  

end

webnark-rails/app/models/service.rb
class Service < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: :slugged

  belongs_to :user

  has_many :answers
  has_many :report_choices, :through => :answers

  accepts_nested_attributes_for :answers, allow_destroy: true
  paginates_per 5
  acts_as_commentable
  make_flaggable
  acts_as_taggable
end

webnark-rails/app/controllers/services_controller.rb
class ServicesController < ApplicationController

  def redirect_back(dest, good_opts = nil, bad_opts = nil)
    begin
      redirect_to :back, good_opts
    rescue ActionController::RedirectBackError
      redirect_to dest, bad_opts
    end
  end

  # The order matters
  #before_filter :authenticate_user!
  before_action :set_service, only: [ :show, :full, :edit, :update, :destroy, :report, :unreport, :moderate ]
  load_and_authorize_resource
  rescue_from CanCan::AccessDenied do |exception|
    redirect_back root_path, {}, { :alert => exception.message }
  end

  before_action :calculate_score, only: [:show, :full]
  after_action :calculate_score, only: [:create, :update]
  after_action :get_screenshot, only: [:create, :update]

  # GET /services
  # GET /services.json
  def index
    @services = Service.all.page(params[:page])
  end

  def search
    services_name = Service.where("(name LIKE ? OR url LIKE ?) AND moderated = 't'", "%#{params[:query]}%", "%#{params[:query]}%")
    services_tags = Service.where(:moderated => true).tagged_with(params[:query])
    @services = Kaminari.paginate_array(services_name + services_tags).page(params[:page])
    render :index
  end

  # GET /services/1
  # GET /services/1.json
  def show
    @good = []
    @bad = []
    @service.answers.each do |answer|
      if answer.report_choice.points > 0
        @good << answer.report_choice
      else
        @bad << answer.report_choice
      end
    end
    @comments = @service.comments.recent.page(params[:page])
  end

  # GET /services/1/full
  def full
    @full_report = true; 

    @answers = {}

    @service.answers.each do |answer|
      category = answer.report_choice.report_item.report_category

      if not @answers.has_key? category.name
        @answers[category.name] = []
      end
      @answers[category.name] << answer
    end

    @comments = @service.comments.recent.page(params[:page])
    render :show
  end

  # GET /services/new
  def new
    @service = Service.new
    @report_categories = ReportCategory.all
  end

  # GET /services/1/edit
  def edit
    @report_categories = ReportCategory.all
  end

  # POST /services
  # POST /services.json
  def create
    @service = Service.new(service_params)

    respond_to do |format|
      if @service.save
        format.html { redirect_to @service, notice: 'Service was successfully created.' }
        format.json { render action: 'show', status: :created, location: @service }
      else
        format.html { render action: 'new' }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /services/1
  # PATCH/PUT /services/1.json
  def update
    respond_to do |format|
      if @service.update(service_params)
        format.html { redirect_to @service, notice: 'Service was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /services/1
  # DELETE /services/1.json
  def destroy
    @service.destroy
    respond_to do |format|
      format.html { redirect_to services_url }
      format.json { head :no_content }
    end
  end

  def add_comment
    service = Service.friendly.find(params[:id])
    service.comments.create(comment_params)
    redirect_to :action => :show, :id => service
  end

  def report
    if user_signed_in?
      current_user.flag(@service, :abuse)
      @service.update_attributes(:flagged => true)
      redirect_to :back, notice: "Service has been reported"
    else
      redirect_to :back, alert: "You must be logged in to report services"
    end
  end

  def unreport
    if user_signed_in?
      current_user.unflag(@service)
      @service.update_attributes(:flagged => false)
      redirect_to :back, notice: "Service has been ureported"
    else
      redirect_to :back, alert: "Oops"
    end
  end

  def moderate
    if @service.update_attributes(:moderated => true)
      redirect_to @service, notice: 'Service has been moderated.'
    else
      redirect_to @service, alert: 'Unable to moderate service.'
    end
  end

  def unmoderated
    @services = Service.where(:moderated => false).page(params[:page])
    render :index
  end

  def flagged
    @services = Service.where(:flagged => true).page(params[:page])
    render :index
  end

  def tagged
    if params[:tag].present?
      @services = Service.where(:moderated => true).tagged_with(params[:tag]).page(params[:page])
    else
      @services = Service.where(:moderated => true).all.page(params[:page])
    end
    render :index
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service
      @service = Service.friendly.find(params[:id])
    end

    def get_screenshot
      ScreenshotWorker.perform_async(@service.url,@service.slug)
    end

    def calculate_score

      @categories = {}
      @category_scores = {}
      @service_scores = {}

      @service.answers.each do |answer|
        category = answer.report_choice.report_item.report_category
        if not @categories.has_key? category.name
          @categories[category.name] = category
        end
      end

      @categories.each_pair do |name, category|

        @category_scores[name] = { :items => {}, :min => 0, :max => 0 }

        category.report_items.each do |item|

          @category_scores[name][:items][item.name] = { :min => 0, :max => 0, :bonus_min => 0, :bonus_max => 0 }
          
          item.report_choices.each do |choice|
            if choice.bonus
              if choice.points >= 0
                @category_scores[name][:items][item.name][:bonus_max] += choice.points
              else
                @category_scores[name][:items][item.name][:bonus_min] += choice.points
              end
            else
              if choice.points >= 0
                @category_scores[name][:items][item.name][:max] = [choice.points, @category_scores[name][:items][item.name][:max]].max
              else
                @category_scores[name][:items][item.name][:min] = [choice.points, @category_scores[name][:items][item.name][:min]].min
              end
            end
          end

          @category_scores[name][:min] += @category_scores[name][:items][item.name][:min] + @category_scores[name][:items][item.name][:bonus_min]
          @category_scores[name][:max] += @category_scores[name][:items][item.name][:max] + @category_scores[name][:items][item.name][:bonus_max]

        end
      end

      @service.answers.each do |answer|
        category = answer.report_choice.report_item.report_category
        points = answer.report_choice.points

        if not @service_scores.has_key? category.name
          @service_scores[category.name] = { :score => 0, :bad => 0, :good => 0 }
        end

        @service_scores[category.name][:score] += points
        if points > 0
          @service_scores[category.name][:good] += points
        else
          @service_scores[category.name][:bad] += points
        end
      end

      score = 0
      total = 0
      @service_scores.each_pair do |category, service_score|
        adjustment = @category_scores[category][:min] * -1
        score += service_score[:score] + adjustment
        total += @category_scores[category][:max] + adjustment
      end

      # Check whether the score has already been set recent
      #if not @service.score or @service.score_updated_at < 1.day.ago
      if total == 0
        score = 0
      else
        score = score.to_f / total.to_f
      end
      if @service.score != score
        @service.score = score
        @service.score_updated_at = Time.now
        @service.save
      end

    end
 
    # Never trust parameters from the scary internet, only allow the white list through.
    def service_params
      params[:service][:answers_attributes].each_pair do |k,v|
        # Need to filter non-selected answers
        if v[:selected].to_s == "0"
          if not v[:id] or v[:id].empty?
            # No id, so ignore
            params[:service][:answers_attributes].delete(k)
          else
            # id exists, so destroy
            params[:service][:answers_attributes][k]["_destroy"] = 1
          end
        end
      end

      # Fix moderated params
      if user_signed_in and current_user.moderator?
        params[:service][:moderated] = true
      else
        params[:service][:moderated] = false
      end

      params.require(:service).permit(
        :name, 
        :description, 
        :tag_list,
        :url, 
        :slug, 
        :hosting_provider, 
        :country, 
        :screenshot_url,
        :answers_attributes => [:id, :service_id, :notes, :report_choice_id, :selected, '_destroy'],
      )
    end

    def comment_params
      if user_signed_in?
        params[:comment][:user_id] = current_user.id
      else
        # TODO - not sure what to do here yet
        return nil
      end
      params.require(:comment).permit(
        :title,
        :user_id,
        :comment
      )
    end
end

webnark-rails/app/helpers/services_helper.rb
module ServicesHelper
  include ActsAsTaggableOn::TagsHelper
end

webnark-rails/app/views/services/_form.html.erb
<%= form_for @service, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field span5' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :description, :class => 'text_field span5', :rows => 3 %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :tags, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :tag_list, :class => 'text_field span5' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :url, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :url, :class => 'text_field span5' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :hosting_provider, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :hosting_provider, :class => 'text_field span5' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :country, :class => 'control-label' %>
    <div class="controls">
      <%= f.country_select :country %>
    </div>
  </div>

  <% @report_categories.all(:order => :name).each do |category| %>
    <div class="block neutral-block"><%= category.name %></div>
    <% category.report_items.each do |item| %>
      <h4><%= item.name %></h4>
      <% item.report_choices.all(:order => "bonus, points").each do |choice| %>
        <% c = choice.points >= 0 ? "text-success" : "text-error" %>
        <%= f.fields_for :answers, choice.answers.find_or_initialize_by(service: @service) do |a| %>
          <div class="row">
            <div class="span1">
              <span class="pull-right"><%= a.check_box :selected %></span>
            </div>
            <div class="span5">
              <strong class="<%= c %>"><%= choice.name %></strong>
            </div>
            <div class="span2">
              <strong class="<%= c %> pull-right"><%= choice.points %><%= " bonus" if choice.bonus %> points</strong>
            </div>
          </div>
          <div class="row">
            <div class="span7 offset1">
              <%= a.text_area :notes, :class => "field span7", :rows => "1", :placeholder => "Optional notes"%>
            </div>
          </div>
          <br/>
          <%= a.hidden_field :service_id, :value => @service.id %>
          <%= a.hidden_field :report_choice_id, :value => choice.id %>
        <% end %>
      <% end %>
    <% end %>
  <% end %>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                services_path, :class => 'btn' %>
  </div>
<% end %>

webnark-rails/app/views/services/_full_report.html.erb
<% @categories.sort.map do |name, category| %>
<% c = @service_scores[name][:score] >= 0 ? "good-block" : "bad-block" %>
<div class="block <%= c %>"><%= image_tag(category.icon_url) %> <%= name %></div>
<p><%= category.description %></p>
<p class="muted">Total score: <%= @service_scores[name][:score] %> | Minimum score: <%= @category_scores[name][:min] %> | Maximum score: <%= @category_scores[name][:max] %></p>

<% @answers[name].each do |answer| %>
 <hr/>
 <% c = answer.report_choice.points >= 0 ? "text-success" : "text-error" %>
 <p class="<%= c %>"><%= answer.report_choice.name %> <span class="pull-right"><%= answer.report_choice.points %> <%= "bonus " if answer.report_choice.bonus %>points</span></p>
 <p><%= answer.report_choice.description %></p>
 <blockquote><%= answer.notes %></blockquote>
<% end %>

<% end %>

webnark-rails/app/views/services/_header.html.erb
<div class="summary">
<table class="summary-table">
<tr>
  <th></th>
  <th>% negative scoring</th>
  <th>% positive scoring</th>
</tr>
<% @categories.sort.map do |name, category| %>
  <%
    if @category_scores[name][:min] == 0
      bad_width = 0
    else
      bad_width = 100 * @service_scores[name][:bad] / @category_scores[name][:min]
    end

    if @category_scores[name][:max] == 0
      good_width = 0
    else
      good_width = 100 * @service_scores[name][:good] / @category_scores[name][:max]
    end
  %>

  <tr>
    <td class="left"><%= name %></td>
    <td><div class="progress"><div class="progress bar-danger pull-right" style="width: <%= bad_width %>%"></div><div class="progress"></td>
    <td><div class="progress"> <div class="progress bar-success" style="width: <%= good_width %>%"></div><div class="progress"></td>
  </tr>
<% end %>

</table>
</div>

<br/>
<p><%= @service.description %></p>
<br/>

webnark-rails/app/views/services/_score.html.erb
<%- model_class = Service -%>
<%
  c = (10 * @service.score).round >= 6 ? "good-block" : "bad-block"
%>
<div class="text-center">
<div class="block <%= c %> score"><%= (10 * @service.score).round %>/10</div>
<br/>
<img alt="screenshot" src="/screenshots/<%= @service.slug %>.png" width="256" height="192"> <!-- 1024x768 scaled down to 25% -->
<br/>
<p><%- if @service.country %>
Hosted in <%= image_tag "flags/#{Country.find_country_by_name(@service.country).alpha2.downcase}.png" %> 
<% end %>
<%- if @service.hosting_provider %>
by <%= @service.hosting_provider %>
<% end %></p>
</div>

webnark-rails/app/views/services/_summary_report.html.erb
<h3>Needs improvement</h3>
<ul class="nav nav-list">

<% @bad.each do |answer| %>
  <li><i class="icon-remove"></i><span class="text-error"> <%= answer.name %></span></li>
<% end %>
</ul>
<h3>Job well done </h3>

<ul class="nav nav-list">
<% @good.each do |answer| %>
  <li><i class="icon-ok"></i><span class="text-success"> <%= answer.name %></span></li>
<% end %>
</ul>

<div class="text-right">
  <%= link_to 'Full Report', full_report_url(id: @service.id), :class => "btn btn-primary" %>
</div>

webnark-rails/app/views/services/edit.html.erb
<%- model_class = Service -%>
<div class="page-header">
<h1>Editing <%= @service.name %></h1>
</div>
<div class="row">
<div class="span8">
<%= render :partial => 'form' %>
</div>
</div>

webnark-rails/app/views/services/index.html.erb
<%- model_class = Service -%>
<%= render 'shared/search' %>

<% @services.each do |service| %>
  <% c = (10 * service.score).round >= 6 ? "good-block" : "bad-block" %>
  <div class="row">
    <div class="span2 text-center">
      <div class="block <%= c %>">
        <h2><%= (10 * service.score).round %>/10</h2>
      </div>
      <p><%- if service.country %>
Hosted in <%= image_tag("flags/#{Country.find_country_by_name(service.country).alpha2.downcase}.png") %>
<% end %>
<%- if service.hosting_provider %>
 by <%= service.hosting_provider %>
<% end %></p>
    </div>
    <div class="span9">
      <h2><%= link_to service.name, service_path(service) %></h2>
      <p class="muted">Last updated by zeroXten <%= service.updated_at %></p>
      <p><%= service.description %></p>
    </div>
  </div>
    <br/>
<% end %>

<div class="row text-center">
<%= paginate @services %>

<p>Can't find the service you're looking for? Help out by adding it.</p>
<% if user_signed_in? %>
<%= link_to 'Add a new service', new_service_path, :class => 'btn btn-primary' %>
<% else %>
<%= link_to 'Sign Up', new_user_registration_path, :class => 'btn btn-primary' %>
<% end %>
</div>

webnark-rails/app/views/services/new.html.erb
<%- model_class = Service -%>
<div class="page-header">
  <h1>New service</h1>
</div>
<%= render :partial => 'form' %>

webnark-rails/app/views/services/show.html.erb
<%- model_class = Service -%>
<%= render 'shared/search' %>

<h1>Security report for <%= link_to @service.name, @service.url %></h1>
<p class="muted">Last updated <%= @service.updated_at %>, added by zeroXten
<% if can? :manage, @service %>
<% if not @service.moderated? %>
  | <%= link_to 'Moderate', moderate_service_path(@service) %> 
<% end %>
<% if @service.flagged %>
  | <%= link_to 'Unreport', unreport_service_path(@service) %>
<% end %>
  | <%= link_to t('.edit', :default => t("helpers.links.edit")), edit_service_path(@service) %> 
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")), service_path(@service), :method => 'delete', :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) } %> 
<% end %>
<% if @service.tags.any? %>
<p>
  Tags: 
  <% @service.tags.each do |tag| %><%= link_to tag.name, tagged_url(:tag => tag.name) %> <% end %>
</p>
<% end %>

<div class="row">
<div class="span9">
  <%= render 'header' %>
  <% if @full_report %>
    <%= render 'full_report' %>
  <% else %>
    <%= render 'summary_report' %>
  <% end %>

  <hr/>
  <h2>Comments</h2>
  <%= render 'comments/list' %>
  <%= form_tag "/services/add_comment", :class => "form-horizontal" do %>
    <%= hidden_field_tag "id", @service.id  %>
    <%= text_field_tag "comment[title]", nil, :class => "span5", :placeholder => "title" %><br/><br/>
    <%= text_area_tag "comment[comment]", nil, :class => "text-area span5", :rows => 5, :placeholder => "comment"  %><br/><br/>
    <%= submit_tag "Add comment" %>
  <% end %>
</div>
<div class="span3">
  <%= render 'score' %>
  <p class="text-center"><%= link_to "report this service", :report_service, :data => { :confirm => 'Report this service?' } %></p>
  <%= render 'shared/community_link'  %>
</div>
</div>