webnark-rails/config/routes.rb
WebnarkRails::Application.routes.draw do

  devise_for :users

  resources :answers
  resources :report_choices
  resources :report_items
  resources :report_categories

  root :to => 'high_voltage/pages#show', id: 'home'

  get '/search/:query', to: 'services#search'
  get '/search', to: 'services#search'

  get '/services/:id/full', to: 'services#full', as: :full_report
  post "/services/add_comment" => "services#add_comment", :as => "add_comment_to_services", :via => [:services]
  get '/services/unmoderated', to: 'services#unmoderated', as: :unmoderated_services
  get '/services/flagged', to: 'services#flagged', as: :flagged_services
  get '/services/:id/report', to: 'services#report', as: :report_service
  get '/services/:id/moderate', to: 'services#moderate', as: :moderate_service
  get '/services/:id/unreport', to: 'services#unreport', as: :unreport_service
  get '/services/tagged' => 'services#tagged', :as => 'tagged'
  resources :services

  get '/comments/:id/report', to: 'comments#report', as: :report_comment
  get '/comments/flagged', to: 'comments#flagged', as: :flagged_comments
  resources :comments

  get '/pages/about', to: 'high_voltage/pages#show', id: 'about'

  

end

webnark-rails/app/models/report_category.rb
class ReportCategory < ActiveRecord::Base
  has_many :report_items
end

webnark-rails/app/controllers/report_categories_controller.rb
class ReportCategoriesController < ApplicationController
  load_and_authorize_resource
  rescue_from CanCan::AccessDenied do |exception|
    begin
      redirect_to :back, :alert => exception.message
    rescue ActionController::RedirectBackError
      redirect_to root_path
    end
  end
  before_action :set_report_category, only: [:show, :edit, :update, :destroy]

  # GET /report_categories
  # GET /report_categories.json
  def index
    @report_categories = ReportCategory.all
  end

  # GET /report_categories/1
  # GET /report_categories/1.json
  def show
  end

  # GET /report_categories/new
  def new
    @report_category = ReportCategory.new
  end

  # GET /report_categories/1/edit
  def edit
  end

  # POST /report_categories
  # POST /report_categories.json
  def create
    @report_category = ReportCategory.new(report_category_params)

    respond_to do |format|
      if @report_category.save
        format.html { redirect_to @report_category, notice: 'Report category was successfully created.' }
        format.json { render action: 'show', status: :created, location: @report_category }
      else
        format.html { render action: 'new' }
        format.json { render json: @report_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /report_categories/1
  # PATCH/PUT /report_categories/1.json
  def update
    respond_to do |format|
      if @report_category.update(report_category_params)
        format.html { redirect_to @report_category, notice: 'Report category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @report_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /report_categories/1
  # DELETE /report_categories/1.json
  def destroy
    @report_category.destroy
    respond_to do |format|
      format.html { redirect_to report_categories_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_report_category
      @report_category = ReportCategory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def report_category_params
      params.require(:report_category).permit(:name, :description, :icon_url)
    end
end

webnark-rails/app/helpers/report_categories_helper.rb
module ReportCategoriesHelper
end

webnark-rails/app/views/report_categories/_form.html.erb
<%= form_for @report_category, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :description, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :icon_url, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :icon_url, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                report_categories_path, :class => 'btn' %>
  </div>
<% end %>

webnark-rails/app/views/report_categories/edit.html.erb
<%- model_class = ReportCategory -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

webnark-rails/app/views/report_categories/index.html.erb
<%- model_class = ReportCategory -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:icon_url) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @report_categories.each do |report_category| %>
      <tr>
        <td><%= link_to report_category.id, report_category_path(report_category) %></td>
        <td><%= report_category.name %></td>
        <td><%= report_category.description %></td>
        <td><%= report_category.icon_url %></td>
        <td><%=l report_category.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_report_category_path(report_category), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      report_category_path(report_category),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_report_category_path,
            :class => 'btn btn-primary' %>

webnark-rails/app/views/report_categories/new.html.erb
<%- model_class = ReportCategory -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

webnark-rails/app/views/report_categories/show.html.erb
<%- model_class = ReportCategory -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @report_category.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @report_category.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:icon_url) %>:</strong></dt>
  <dd><%= @report_category.icon_url %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              report_categories_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_report_category_path(@report_category), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              report_category_path(@report_category),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>