webnark-rails/config/routes.rb
WebnarkRails::Application.routes.draw do

  devise_for :users

  resources :answers
  resources :report_choices
  resources :report_items
  resources :report_categories

  root :to => 'high_voltage/pages#show', id: 'home'

  get '/search/:query', to: 'services#search'
  get '/search', to: 'services#search'

  get '/services/:id/full', to: 'services#full', as: :full_report
  post "/services/add_comment" => "services#add_comment", :as => "add_comment_to_services", :via => [:services]
  get '/services/unmoderated', to: 'services#unmoderated', as: :unmoderated_services
  get '/services/flagged', to: 'services#flagged', as: :flagged_services
  get '/services/:id/report', to: 'services#report', as: :report_service
  get '/services/:id/moderate', to: 'services#moderate', as: :moderate_service
  get '/services/:id/unreport', to: 'services#unreport', as: :unreport_service
  get '/services/tagged' => 'services#tagged', :as => 'tagged'
  resources :services

  get '/comments/:id/report', to: 'comments#report', as: :report_comment
  get '/comments/flagged', to: 'comments#flagged', as: :flagged_comments
  resources :comments

  get '/pages/about', to: 'high_voltage/pages#show', id: 'about'

  

end

webnark-rails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "thunr.com" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="brand" href="/"><%= image_tag("thunr-logo.png") %></a>
          <!-- <a class="brand" href="/">Thunr.com</a> -->
 <!-- Start of the nav bar content -->
      <div class="nav-collapse"><!-- Other nav bar content -->
        <!-- The drop down menu -->
        <ul class="nav pull-right"
          <li class="divider-vertical"></li>
          <li><%= link_to "About", page_path('about') %></li>
          <% if user_signed_in? %>
          <% if current_user.moderator? or current_user.admin? %>
          <li class="divider-vertical"></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Moderator <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li role="presentation"><%= link_to 'Add a new service', new_service_path %></li>
              <li role="presentation"><%= link_to "Unmoderated services", unmoderated_services_path %></li>
              <li role="presentation"><%= link_to "Flagged services", flagged_services_path%></li>
              <li role="presentation"><%= link_to "Flagged comments", flagged_comments_path %></li>
            </ul>
          </li>
          <% end %>
          <% if current_user.admin? %>
          <li class="divider-vertical"></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Admin <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li role="presentation"><%= link_to 'Report Categories', report_categories_path() %></li>
              <li role="presentation"><%= link_to 'Report Items', report_items_path() %></li>
              <li role="presentation"><%= link_to 'Report Choices', report_choices_path() %></li>
              <li role="presentation"><%= link_to 'Answers', answers_path() %></li>
            </ul>
          </li>
          <% end %>
          <li class="divider-vertical"></li>
          <li class="dropdown">
            <a class="dropdown-toggle" href="#" data-toggle="dropdown"><%= current_user.username %> <strong class="caret"></strong></a>
            <ul class="dropdown-menu" style="padding: 15px;">
              <li role="presentation"><%= link_to('Account', edit_user_registration_path(current_user)) %></li>
              <li><hr/></li>
              <li role="presentation"><%= link_to('Sign out', destroy_user_session_path, :method => :delete) %></li>
            </ul>
          </li>
          <% else %>
          <li class="divider-vertical"></li>
          <li><%= link_to 'Sign Up', new_user_registration_path %></li>
          <li class="divider-vertical"></li>
          <li class="dropdown">
            <a class="dropdown-toggle" href="#" data-toggle="dropdown">Sign In <strong class="caret"></strong></a>
            <div class="dropdown-menu" style="padding: 15px;">
              <%= form_for("user", :url => user_session_path) do |f| %>
                <%= f.text_field :email, :placeholder => "username" %>
                <%= f.password_field :password, :placeholder => "password" %>
                <%= f.check_box :remember_me, :class => "pull-left", :style => "margin-right: 10px;" %>
                <%= f.label :remember_me, :class => "string optional" %>
                <%= f.submit 'Sign in', :class => "btn btn-primary"%>
                <br/><br/>
                <%= link_to "Forgot your password?", new_password_path('user') %>
              <% end %>
            </div>
          </li>
          <% end %>
        </ul>
      </div>
        </div>
      </div>
    </div>

    <div class="container">


          <%= bootstrap_flash %>
          <%= yield %>

        <hr/>
        <div class="footer text-center">
         <p><a href="#">Privacy</a> | <a href="#">Contact</a> |<a href="#"> Further Information</a> | <a href="#">References</a> | <a href="#">Creative Commons blah</a></p>
         <p><a class="muted" href="http://getbootstrap.com/2.3.2/">Made pretty using Bootstrapp</a> | <a class="muted" href="http://rubyonrails.org/">Powered by Ruby on Rails</a> | <a class="muted" href="http://iconpharm.com/">Icons by IconPharm</a></p>
        </div>


    </div> <!-- /container -->


  </body>
</html>