webnark-rails/config/routes.rb
WebnarkRails::Application.routes.draw do

  devise_for :users

  resources :answers
  resources :report_choices
  resources :report_items
  resources :report_categories

  root :to => 'high_voltage/pages#show', id: 'home'

  get '/search/:query', to: 'services#search'
  get '/search', to: 'services#search'

  get '/services/:id/full', to: 'services#full', as: :full_report
  post "/services/add_comment" => "services#add_comment", :as => "add_comment_to_services", :via => [:services]
  get '/services/unmoderated', to: 'services#unmoderated', as: :unmoderated_services
  get '/services/flagged', to: 'services#flagged', as: :flagged_services
  get '/services/:id/report', to: 'services#report', as: :report_service
  get '/services/:id/moderate', to: 'services#moderate', as: :moderate_service
  get '/services/:id/unreport', to: 'services#unreport', as: :unreport_service
  get '/services/tagged' => 'services#tagged', :as => 'tagged'
  resources :services

  get '/comments/:id/report', to: 'comments#report', as: :report_comment
  get '/comments/flagged', to: 'comments#flagged', as: :flagged_comments
  resources :comments

  get '/pages/about', to: 'high_voltage/pages#show', id: 'about'

  

end

webnark-rails/app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :service
  belongs_to :report_choice
end

webnark-rails/app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  load_and_authorize_resource
  rescue_from CanCan::AccessDenied do |exception|
    begin
      redirect_to :back, :alert => exception.message
    rescue ActionController::RedirectBackError
      redirect_to root_path
    end
  end
  before_action :set_answer, only: [:show, :edit, :update, :destroy]

  # GET /answers
  # GET /answers.json
  def index
    @answers = Answer.all
  end

  # GET /answers/1
  # GET /answers/1.json
  def show
  end

  # GET /answers/new
  def new
    @answer = Answer.new
  end

  # GET /answers/1/edit
  def edit
  end

  # POST /answers
  # POST /answers.json
  def create
    @answer = Answer.new(answer_params)

    respond_to do |format|
      if @answer.save
        format.html { redirect_to @answer, notice: 'Answer was successfully created.' }
        format.json { render action: 'show', status: :created, location: @answer }
      else
        format.html { render action: 'new' }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /answers/1
  # PATCH/PUT /answers/1.json
  def update
    respond_to do |format|
      if @answer.update(answer_params)
        format.html { redirect_to @answer, notice: 'Answer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /answers/1
  # DELETE /answers/1.json
  def destroy
    @answer.destroy
    respond_to do |format|
      format.html { redirect_to answers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_answer
      @answer = Answer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def answer_params
      params.require(:answer).permit(:service_id, :report_choice_id, :notes)
    end
end

webnark-rails/app/helpers/answers_helper.rb
module AnswersHelper
end

webnark-rails/app/views/answers/_form.html.erb
<%= form_for @answer, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :service_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :service_id, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :report_choice_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :report_choice_id, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :notes, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :notes, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                answers_path, :class => 'btn' %>
  </div>
<% end %>

webnark-rails/app/views/answers/edit.html.erb
<%- model_class = Answer -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

webnark-rails/app/views/answers/index.html.erb
<%- model_class = Answer -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:service_id) %></th>
      <th><%= model_class.human_attribute_name(:report_choice_id) %></th>
      <th><%= model_class.human_attribute_name(:notes) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @answers.each do |answer| %>
      <tr>
        <td><%= link_to answer.id, answer_path(answer) %></td>
        <td><%= answer.service_id %></td>
        <td><%= answer.report_choice_id %></td>
        <td><%= answer.notes %></td>
        <td><%=l answer.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_answer_path(answer), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      answer_path(answer),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_answer_path,
            :class => 'btn btn-primary' %>

webnark-rails/app/views/answers/new.html.erb
<%- model_class = Answer -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

webnark-rails/app/views/answers/show.html.erb
<%- model_class = Answer -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:service_id) %>:</strong></dt>
  <dd><%= @answer.service_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:report_choice_id) %>:</strong></dt>
  <dd><%= @answer.report_choice_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:notes) %>:</strong></dt>
  <dd><%= @answer.notes %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              answers_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_answer_path(@answer), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              answer_path(@answer),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>